USE [master]
GO
/****** Object:  Database [Altiora]    Script Date: 20/06/2024 22:11:55 ******/
CREATE DATABASE [Altiora]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Altiora', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Altiora.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Altiora_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Altiora_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Altiora] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Altiora].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Altiora] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Altiora] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Altiora] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Altiora] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Altiora] SET ARITHABORT OFF 
GO
ALTER DATABASE [Altiora] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Altiora] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Altiora] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Altiora] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Altiora] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Altiora] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Altiora] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Altiora] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Altiora] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Altiora] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Altiora] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Altiora] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Altiora] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Altiora] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Altiora] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Altiora] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Altiora] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Altiora] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Altiora] SET  MULTI_USER 
GO
ALTER DATABASE [Altiora] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Altiora] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Altiora] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Altiora] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Altiora] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Altiora] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Altiora] SET QUERY_STORE = ON
GO
ALTER DATABASE [Altiora] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Altiora]
GO
/****** Object:  Table [dbo].[Article]    Script Date: 20/06/2024 22:11:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Article](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Code] [nvarchar](50) NOT NULL,
	[UnitPrice] [decimal](18, 2) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Article] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Client]    Script Date: 20/06/2024 22:11:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NULL,
	[Identification] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](128) NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 20/06/2024 22:11:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Code] [nvarchar](50) NOT NULL,
	[ClientId] [int] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetail]    Script Date: 20/06/2024 22:11:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetail](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[ArticleId] [int] NOT NULL,
	[UnitPrice] [decimal](18, 2) NOT NULL,
	[Quantity] [int] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_OrderDetail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Article] ON 
GO
INSERT [dbo].[Article] ([Id], [Name], [Code], [UnitPrice], [IsDeleted]) VALUES (1, N'Monitor', N'12345678998', CAST(120.00 AS Decimal(18, 2)), 0)
GO
INSERT [dbo].[Article] ([Id], [Name], [Code], [UnitPrice], [IsDeleted]) VALUES (2, N'Teclado', N'64654654454', CAST(12.00 AS Decimal(18, 2)), 0)
GO
SET IDENTITY_INSERT [dbo].[Article] OFF
GO
SET IDENTITY_INSERT [dbo].[Client] ON 
GO
INSERT [dbo].[Client] ([Id], [FirstName], [LastName], [Identification], [Email], [IsDeleted]) VALUES (1, N'Guido', N'Guerrero', N'1803575214', N'guido_guerrero_d@hotmail.com', 0)
GO
INSERT [dbo].[Client] ([Id], [FirstName], [LastName], [Identification], [Email], [IsDeleted]) VALUES (2, N'Juan', N'Benalcazar', N'1801016898', N'mai@mail.com', 0)
GO
SET IDENTITY_INSERT [dbo].[Client] OFF
GO
SET IDENTITY_INSERT [dbo].[Order] ON 
GO
INSERT [dbo].[Order] ([Id], [Date], [Code], [ClientId], [IsDeleted]) VALUES (1, CAST(N'2024-06-19T00:00:00.0000000' AS DateTime2), N'OC-00000001', 1, 0)
GO
INSERT [dbo].[Order] ([Id], [Date], [Code], [ClientId], [IsDeleted]) VALUES (2, CAST(N'2024-06-18T00:00:00.0000000' AS DateTime2), N'OC-00000002', 1, 0)
GO
SET IDENTITY_INSERT [dbo].[Order] OFF
GO
SET IDENTITY_INSERT [dbo].[OrderDetail] ON 
GO
INSERT [dbo].[OrderDetail] ([Id], [OrderId], [ArticleId], [UnitPrice], [Quantity], [IsDeleted]) VALUES (1, 1, 1, CAST(110.00 AS Decimal(18, 2)), 1, 0)
GO
INSERT [dbo].[OrderDetail] ([Id], [OrderId], [ArticleId], [UnitPrice], [Quantity], [IsDeleted]) VALUES (2, 1, 2, CAST(13.00 AS Decimal(18, 2)), 2, 0)
GO
SET IDENTITY_INSERT [dbo].[OrderDetail] OFF
GO
ALTER TABLE [dbo].[Article] ADD  CONSTRAINT [DF_Article_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[Client] ADD  CONSTRAINT [DF_Client_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[Order] ADD  CONSTRAINT [DF_Order_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[OrderDetail] ADD  CONSTRAINT [DF_OrderDetail_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Client] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Client] ([Id])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Client]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Article] FOREIGN KEY([ArticleId])
REFERENCES [dbo].[Article] ([Id])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Article]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetail_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderDetail_Order]
GO
USE [master]
GO
ALTER DATABASE [Altiora] SET  READ_WRITE 
GO
